formatting:
  MaximumLineLength:
    maxLineLength: 180
  SpacingAroundKeyword:
      active: false
      autoCorrect: false
  NoLineBreakAfterElse:
      active: false
      autoCorrect: false
  SpacingAroundCurly:
        active: false
        autoCorrect: false
  Indentation:
        active: false
        autoCorrect: false
